apiVersion: batch/v1
kind: Job
metadata:
  generatedName: my-finalizer-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: post-install-job
          image: "registry.access.redhat.com/ubi8/ubi-minimal:latest"              
          command: 
          - /bin/sh
          - -c 
          - |
            echo "WELCOME TO the post installation hook for ArgoCD "
            echo "-------------------------------------------------"
            echo "Here we could now do initialization work."
            echo "Like filling our DB with some data or what's so ever"
            echo "..."

            sleep 10
