namePrefix: dev-
commonLabels:
  variant: development


# replace the image tag of the container with latest
images:
- digest: sha256:4aa9f7090950f01742ff2ae3dc3ce2f4cd45a6dc07d3c168d1ecde91914b7d46
  name: quay.io/wpernath/quarkus-simple
  newName: quay.io/wpernath/quarkus-simple-wow
- name: quay.io/wpernath/simple-quarkus
  newTag: latest
- digest: sha256:a70384d14301b7edc28119d5addf667505bca30f99feade770c15a2b0616dfb3
  name: quay.io/wpernath/simple-quarkus:latest
  newName: quay.io./wpernath/simple-quarkus-wow

# apply a patch to replace the Host of the Route
#- patch: |-
#    - op: replace
#      path: /spec/host
#      value: art-test.apps-crc.testing
#  target:
#    kind: Route
# this patch needs to be done, because kustomize does not change 
# the route target service name
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-simple
  target:
    kind: Route
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
